version: '3'
services:
  webapp:
    container_name: Spring_Batch
    image: spring/batch-sample:latest
    # networks:
    #   DockerLAN:
    #     ipv4_address: 10.18.0.10
    networks:
      - 'DockerLAN'
    depends_on:
      - database
    ports:
      - "80:8080"
  database:
    container_name: Spring_Batch_BD
    hostname: mysql01
    image: mysql:5.6
    # networks:
    #   DockerLAN:
    #     ipv4_address: 10.18.0.5
    networks:
      - 'DockerLAN'
    environment:
      MYSQL_DATABASE: spring_batch
      MYSQL_ROOT_PASSWORD: R00tR00t
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ~/Volumes/spring_batch:/var/lib/mysql
networks:
 DockerLAN:
  driver: bridge
  # ipam:
  #   config:
  #     - subnet: 172.18.0.0/16
  #       Gateway: 172.18.0.1
